############# English navigation ##############

# main menu
[[main]]
name = "Blog"
url = "/"
weight = 1

[[main]]
name = "Moi"
url = "about/"
weight = 2

[[main]]
weight = 3
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Catégories"
url = "categories/"

[[main]]
parent = "Pages"
name = "Ressources & Liens intéressants"
url = "ressources/"

# footer menu
[[footer]]
name = "A propos"
url = "about/"
weight = 1

